### ISSUE TITLE
Scientific papers using mybinder.org

### ISSUE THREAD

**Issue by betatim** [choldgraf/scipy_proceedings#5]
https://arxiv.org/search/?query=mybinder.org&searchtype=all&order=-announced_date_first&size=50

Only finds two papers. Google scholar finds a few more.

* https://arxiv.org/abs/1710.04509
* https://arxiv.org/abs/1803.01944  The construction and use of LISA sensitivity curves

**Comment by choldgraf** [comment]
there's also https://www.frontiersin.org/articles/10.3389/fnsys.2017.00061/full :-D

**Comment by jzf2101** [comment]
Also the IJCAI paper listed in the paper

**Comment by jzf2101** [comment]
Can we close for now?

**Comment by choldgraf** [comment]
did we get all of these listed in the paper? If so, I'm +1 to close

**Comment by jzf2101** [comment]
We didn't I can update the PR based on that and then close.

**Comment by jzf2101** [comment]
We can close then?

**Comment by choldgraf** [comment]
yes! :-)
